openapi: 3.1.0
x-stoplight:
  id: kwpgc1mg8eeju
info:
  title: newapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}_copy':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: qsrjga9zgalps
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: pfom1hy6ssr2m
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: h9vpgcms921ch
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-test
      x-stoplight:
        id: jznuehs2h9fzm
    delete:
      summary: Your DELETE endpoint
      x-stoplight:
        id: ow7lzl0vqyqvo
      tags: []
      responses: {}
      operationId: delete-test
      requestBody:
        content:
          application/javascript:
            schema:
              type: object
              required:
                - wefrwgth
              properties:
                wefrwgth:
                  type: string
                  x-stoplight:
                    id: osoo4qvdcxyln
                  description: nalanda
                wefwrgeth:
                  x-stoplight:
                    id: sv0qvk9w13778
                  oneOf:
                    - type: object
                      x-stoplight:
                        id: 4b7sc16nx158f
                      required:
                        - dfge
                      properties:
                        dfge:
                          type: string
                          x-stoplight:
                            id: nuaruqaj5055t
                    - type: object
                      x-stoplight:
                        id: 2vs4rxkzwvq1i
                      properties:
                        wefrgthy:
                          type: string
                          x-stoplight:
                            id: m1p5s103cod1c
                    - type: integer
                      x-stoplight:
                        id: d7r13876gogoz
                wqefrget:
                  type: string
                  x-stoplight:
                    id: 7xkrynvt673io
            examples:
              Example 1:
                value:
                  wefrwgth: string
                  wefwrgeth:
                    dfge: change
                  wqefrget: string
    trace:
      summary: Your TRACE endpoint
      tags: []
      responses: {}
      operationId: trace-test
      x-stoplight:
        id: gsz4ydhvi3t0o
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: 71rj0zf3j0kwz
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: ptiqn79zrt7ig
        firstName:
          type: string
          x-stoplight:
            id: m92alz52qvg43
        lastName:
          type: string
          x-stoplight:
            id: lfszg3e9subqf
        email:
          type: string
          format: email
          x-stoplight:
            id: mbe78p8m2bern
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: ykmya6oapm853
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: dgcui0lu1m5ih
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 5fw6gadbpnn8f
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
